name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches: [main]
  schedule: 
    - cron: '34 2 * * *'
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/${{ github.repository }}:latest
          VER=`docker run ghcr.io/${{ github.repository }}:latest caddy version | cut -d ' ' -f 1`
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:$VER
          docker manifest inspect ghcr.io/${{ github.repository }}:$VER || docker push ghcr.io/${{ github.repository }}:$VER

      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'caddy'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
